{{ if .Values.reaper.podreaper }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reaper
  namespace: {{ .Release.Namespace }}
---
{{ end }}
{{ if .Values.reaper.pdbreaper }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pdb-reaper
  namespace: {{ .Release.Namespace }}
---
{{ end }}
{{ if .Values.reaper.nodereaper }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-reaper
  namespace: {{ .Release.Namespace }}
{{ end }}
